blank_issues_enabled: false
contact_links:
  - name: ğŸ” Search in Discussions
    url: https://github.com/themeselection/flyonui/discussions?discussions_q=
    about: First see if there's an existing topic in Discussions.
  - name: ğŸ” Search in Issues
    url: https://github.com/themeselection/flyonui/issues?q=is%3Aissue
    about: If you found a bug, first see if there's an existing issue about it.
  - name: â“ Ask a new question in Discussions
    url: https://github.com/themeselection/flyonui/discussions/new?category=q-a
    about: If you have a new question and you couldn't find answers.
  - name: ğŸ’¡ Ideas / Feature request
    url: https://github.com/themeselection/flyonui/discussions/new?category=ideas-request-new-feature
    about: If you want to suggest a new idea or if you want a new feature to be added to flyonui, let's talk about it in Discussions forum
